#!/usr/bin/env python
r"""Emit the prompt-(B) LLM-plausibility panel over all nine LLM-scored datasets.

Data source is shared with scripts/make_llm_win_fig.py (single source of truth):
  * 6 additional datasets : results/llm_coherence_all_v2.csv (on disk)
  * 3 original datasets   : the main-paper LLM table, mirrored in that script
Both are the faithful naming-then-confidence protocol (prompt B, Hu et al. 2025).

Self-check: before emitting, the script recomputes the published six-dataset panel and the
published nine-dataset aggregate and refuses to write if either disagrees. This guarantees
the new rows are produced by the same convention as the numbers already in the paper.

Run: python scripts/build_llm_table_all9.py
Out: prints the panel-(B) LaTeX rows to stdout.
     They are pasted rather than \input because booktabs' \cmidrule expands 
oalign,
     which misfires when pulled into the middle of an existing tabular via \input.
"""
import os
import sys

import numpy as np
import pandas as pd

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(HERE, "scripts"))

from make_llm_win_fig import load_matrix  # noqa: E402  (shared data source)

# column order used in the prompt-(B) panel
COLS = ["PRISM", "MALLET", "NMF", "cNMF", "scHPF", "ProdLDA"]
SIX = ["hemogenic_endothelium", "pancreas", "gastrulation_e75",
       "gastrulation", "gastrulation_erythroid", "bonemarrow"]
NINE = ["breast_cancer", "pbmc3k", "zeisel_brain"] + SIX
DISPLAY = {
    "breast_cancer": "BreastCancer", "pbmc3k": "PBMC3k", "zeisel_brain": "Zeisel brain",
    "hemogenic_endothelium": "Hemogenic Endo.", "pancreas": "Pancreas",
    "gastrulation_e75": "Gastrulation E7.5", "gastrulation": "Gastrulation (full)",
    "gastrulation_erythroid": "Gastrulation Eryth.", "bonemarrow": "Bonemarrow",
}


def f3(v):
    """0.939 -> .939"""
    return f"{v:.3f}".lstrip("0")


def ranks(M):
    """per-dataset ranks, 1 = best (highest score); ties share the average rank."""
    return M.rank(axis=1, ascending=False, method="average")


def summarize(M):
    R = ranks(M)
    # ddof=1 (sample std) is the published convention: it reproduces the six-dataset
    # panel's stds exactly, whereas ddof=0 comes out sqrt(5/6) too low.
    return M.mean(), M.median(), M.std(ddof=1), R.mean()


def check(label, got, want, tol):
    ok = abs(got - want) <= tol
    print(f"  {'OK ' if ok else 'BAD'} {label:38} got {got:.3f}  published {want:.3f}")
    return ok


M = load_matrix()[COLS]
M9 = M.loc[NINE]
M6 = M.loc[SIX]

print("== consistency check vs the six-dataset panel ==")
m6, _, s6, r6 = summarize(M6)
ok = True
for meth, wr, wm, ws in [("PRISM", 1.92, .875, .054), ("MALLET", 2.25, .871, .057),
                         ("NMF", 3.33, .846, .041), ("cNMF", 4.33, .773, .104),
                         ("scHPF", 3.17, .858, .051), ("ProdLDA", 6.00, .338, .194)]:
    ok &= check(f"{meth} mean rank (6ds)", r6[meth], wr, 0.02)
    ok &= check(f"{meth} mean (6ds)", m6[meth], wm, 0.002)
    ok &= check(f"{meth} std (6ds)", s6[meth], ws, 0.002)

print("\n== consistency check vs the nine-dataset aggregate ==")
m9, med9, s9, r9 = summarize(M9)
for meth, wm, wmed, wr in [("PRISM", .879, .886, 1.72), ("MALLET", .861, .882, 2.61)]:
    ok &= check(f"{meth} mean (9ds)", m9[meth], wm, 0.002)
    ok &= check(f"{meth} median (9ds)", med9[meth], wmed, 0.002)
    ok &= check(f"{meth} mean rank (9ds)", r9[meth], wr, 0.02)

if not ok:
    sys.exit("\nSELF-CHECK FAILED: recomputation disagrees with the published numbers. "
             "Not writing the fragment.")
print("\nAll self-checks passed. Emitting all-nine panel.\n")

lines = ["% AUTO-GENERATED by scripts/build_llm_table_all9.py -- do not hand-edit numbers.",
         "% Prompt-(B) naming-then-confidence panel over ALL NINE LLM-scored datasets."]
for ds in NINE:
    row = M9.loc[ds]
    order = row.sort_values(ascending=False)
    best_v, second_v = order.iloc[0], order[order < order.iloc[0]].max() if (order < order.iloc[0]).any() else None
    cells = []
    for m in COLS:
        v = row[m]
        s = f3(v)
        if np.isclose(v, best_v):
            s = f"\\best{{{s}}}"
        elif second_v is not None and np.isclose(v, second_v):
            s = f"\\secondbest{{{s}}}"
        if m == "PRISM" and row["PRISM"] > row["MALLET"]:
            s += "\\prismwin"
        cells.append(s)
    lines.append(f"{DISPLAY[ds]:<20}& " + " & ".join(cells) + r" \\")

lines.append(r"\cmidrule(lr){1-7}")


def summary_row(label, series, lower_better):
    order = series.sort_values(ascending=lower_better)
    best_v = order.iloc[0]
    rest = order[~np.isclose(order, best_v)]
    second_v = rest.iloc[0] if len(rest) else None
    cells = []
    for m in COLS:
        v = series[m]
        s = f"{v:.2f}" if lower_better else f3(v)
        if np.isclose(v, best_v):
            s = f"\\best{{{s}}}"
        elif second_v is not None and np.isclose(v, second_v):
            s = f"\\secondbest{{{s}}}"
        cells.append(s)
    return f"{label} & " + " & ".join(cells) + r" \\"


lines.append(summary_row(r"\textit{mean rank} $\downarrow$", r9, True))
ms_cells = []
best_m = m9.max()
second_m = m9[m9 < best_m].max()
for m in COLS:
    s = f"{f3(m9[m])}\\,({f3(s9[m])})"
    if np.isclose(m9[m], best_m):
        s = f"\\best{{{s}}}"
    elif np.isclose(m9[m], second_m):
        s = f"\\secondbest{{{s}}}"
    ms_cells.append(s)
lines.append(r"\textit{mean\,(std)} & " + " & ".join(ms_cells) + r" \\")

print("\n".join(lines))
print("\n^ LaTeX rows for the prompt-(B) panel.")
