"""Shared definitions and aggregate statistics for the GO-BP benchmark at a single
unified metric convention (opt0), all datasets scored by our 10-seed reproduction
(full_metrics_combined_4config.csv).

This module is imported by build_robustness_agg_15ds.py for its dataset lists, method
labels and aggregation helpers, so those cannot drift between the two generators.

Running it directly also emits two combined-table fragments that the paper does not
currently include (it uses the split tables from build_split_tables.py instead):
  - paper/figures/tab_unified_9ds_opt0.tex
  - paper/figures/tab_unified_15ds_opt0.tex
  - aggregate stats (mean rank, never-worst, geom composite, PRISM Welch win/tie/loss) to stdout.
Config = opt0 (best on the 15-dataset benchmark; the beta-faithful config). Numbers are computed,
never hand-entered. NaN (no significant enrichment) renders as "---" and is excluded from ranking.
"""
from __future__ import annotations
import sys
from pathlib import Path
import numpy as np, pandas as pd
from scipy import stats

WS = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(Path(__file__).resolve().parent))
from paths import results_dir, figures_dir  # noqa: E402
AGG = results_dir() / "full_metrics_combined_4config.csv"
PS = results_dir() / "full_metrics_perseed.csv"
OUT = figures_dir()                          # paper/figures (release layout; created if missing)

CFG = "o0"
METHODS = ["PRISM", "MALLET", "NMF", "cNMF", "scHPF", "ProdLDA"]
PREF = {"PRISM": f"PRISM{CFG}", "MALLET": f"MALLET{CFG}", "NMF": "NMF", "cNMF": "cNMF",
        "scHPF": "scHPF", "ProdLDA": "ProdLDA"}
PS_VAR = {"PRISM": "PRISM_opt0", "MALLET": "MALLET_opt0", "NMF": "NMF", "cNMF": "cNMF",
          "scHPF": "scHPF", "ProdLDA": "ProdLDA"}
METR = ["coh", "cov", "str"]
NINE = ["breast_cancer", "pbmc3k", "zeisel_brain", "hemogenic_endothelium", "pancreas",
        "gastrulation_e75", "gastrulation", "gastrulation_erythroid", "bonemarrow"]
PRETTY = {"breast_cancer": "BreastCancer", "pbmc3k": "PBMC3k", "zeisel_brain": "Zeisel brain",
          "hemogenic_endothelium": "Hemogenic Endo.", "pancreas": "Pancreas",
          "gastrulation_e75": "Gastrulation E7.5", "gastrulation": "Gastrulation (full)",
          "gastrulation_erythroid": "Gastrulation Eryth.", "bonemarrow": "Bonemarrow",
          "paul15": "Paul HSC", "dentategyrus": "Dentate Gyrus", "pbmc68k": "PBMC68k",
          "endoderm_diff": "Endoderm diff.", "ventral_neuron_diff": "Ventral neuron",
          "mouse_hspc": "Mouse HSPC"}


def val(df, ds, m, me):
    c = f"{PREF[m]}_{me}"
    return df.loc[ds, c] if c in df.columns else np.nan


def fmt(x, me):
    if pd.isna(x):
        return "---"
    return f"{x:.2f}" if me == "str" else f"{x:.3f}".lstrip("0") or "0"


def build_table(df, datasets, label, caption):
    """LaTeX tabular: bold best, underline 2nd, dagger where PRISM>MALLET per cell."""
    lines = [r"\begin{tabular}{l *{3}{c} *{3}{c} *{3}{c} *{3}{c} *{3}{c} *{3}{c}}", r"\toprule",
             "& " + " & ".join(rf"\multicolumn{{3}}{{c}}{{{'\\textbf{PRISM-GEP}' if m=='PRISM' else m}}}" for m in METHODS) + r" \\",
             "".join(rf"\cmidrule(lr){{{2+3*i}-{4+3*i}}}" for i in range(6)),
             r"\textbf{Dataset} & " + " & ".join(["Coh & Cov & Str"] * 6) + r" \\", r"\midrule"]
    for ds in datasets:
        cells = []
        for me in METR:
            vals = {m: val(df, ds, m, me) for m in METHODS}
            defined = {m: v for m, v in vals.items() if pd.notna(v)}
            best = max(defined.values()) if defined else None
            second = sorted(set(defined.values()), reverse=True)[1] if len(set(defined.values())) > 1 else None
            for m in METHODS:
                s = fmt(vals[m], me)
                if pd.notna(vals[m]) and best is not None and abs(vals[m] - best) < 1e-9:
                    s = rf"\best{{{s}}}"
                elif pd.notna(vals[m]) and second is not None and abs(vals[m] - second) < 1e-9:
                    s = rf"\secondbest{{{s}}}"
                if m == "PRISM" and pd.notna(vals["PRISM"]) and pd.notna(vals["MALLET"]) and vals["PRISM"] > vals["MALLET"]:
                    s += r"\prismwin"
                cells.append((m, me, s))
        # reorder cells to method-major (Coh Cov Str per method)
        row = [PRETTY.get(ds, ds)]
        for m in METHODS:
            for me in METR:
                row.append(next(s for mm, mee, s in cells if mm == m and mee == me))
        lines.append(" & ".join(row) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    frag = (rf"% AUTO-GENERATED by scripts/build_unified_table1.py -- do not hand-edit numbers." + "\n"
            + "\n".join(lines) + "\n")
    (OUT / f"tab_unified_{label}.tex").write_text(frag, encoding="utf-8")
    return frag


def aggregate(df, datasets, drop_degenerate=True):
    """mean rank + never-worst per method; PRISM composite; over defined cells."""
    ranks = {m: [] for m in METHODS}
    last = {m: 0 for m in METHODS}
    prism_last = []
    cells = 0
    norm = {m: [] for m in METHODS}  # min-max normalized for composite
    for ds in datasets:
        for me in METR:
            vals = {m: val(df, ds, m, me) for m in METHODS}
            defined = [v for v in vals.values() if pd.notna(v)]
            if not defined:
                continue
            # a cell where <2 methods enrich is degenerate (no ranking power)
            if drop_degenerate and sum(pd.notna(v) for v in vals.values()) < 3:
                continue
            cells += 1
            ser = pd.Series({m: (v if pd.notna(v) else -1e9) for m, v in vals.items()})
            rk = ser.rank(ascending=False, method="min")
            worst = rk.max()
            lo, hi = min(defined), max(defined)
            for m in METHODS:
                ranks[m].append(rk[m])
                if rk[m] == worst:
                    last[m] += 1
                v = vals[m]
                norm[m].append((v - lo) / (hi - lo) if (pd.notna(v) and hi > lo) else (0.0 if pd.isna(v) else 1.0))
            if rk["PRISM"] == worst:
                prism_last.append(f"{ds}/{me}")
    mr = {m: float(np.mean(ranks[m])) for m in METHODS}
    comp = {m: float(np.exp(np.mean(np.log(np.clip(norm[m], 1e-6, 1))))) for m in METHODS}
    return mr, last, cells, prism_last, comp


def agg_table(df, datasets, tag):
    """Per-method mean rank (+bootstrap CI over datasets), geometric composite, worst-axis.
    Worst-axis = min over the 3 metrics of the method's mean within-dataset min-max score."""
    import random
    random.seed(0)
    # per (ds, metric) normalized scores + ranks
    normcell = {m: {} for m in METHODS}  # (ds,me) -> normalized value
    rankcell = {m: {} for m in METHODS}
    ds_cells = {ds: [] for ds in datasets}
    for ds in datasets:
        for me in METR:
            vals = {m: val(df, ds, m, me) for m in METHODS}
            if sum(pd.notna(v) for v in vals.values()) < 3:
                continue
            defined = [v for v in vals.values() if pd.notna(v)]
            lo, hi = min(defined), max(defined)
            ser = pd.Series({m: (v if pd.notna(v) else -1e9) for m, v in vals.items()})
            rk = ser.rank(ascending=False, method="min")
            ds_cells[ds].append((ds, me))
            for m in METHODS:
                v = vals[m]
                normcell[m][(ds, me)] = ((v - lo) / (hi - lo) if (pd.notna(v) and hi > lo) else (0.0 if pd.isna(v) else 1.0))
                rankcell[m][(ds, me)] = rk[m]
    cells = [c for ds in datasets for c in ds_cells[ds]]
    def mean_rank(m, cs): return np.mean([rankcell[m][c] for c in cs]) if cs else np.nan
    def geom(m, cs): return float(np.exp(np.mean(np.log(np.clip([normcell[m][c] for c in cs], 1e-6, 1)))))
    def worst_axis(m):
        per = []
        for me in METR:
            xs = [normcell[m][(ds, me)] for ds in datasets for c in [(ds, me)] if c in normcell[m]]
            if xs: per.append(np.mean(xs))
        return min(per) if per else np.nan
    rows = {}
    for m in METHODS:
        boots = []
        for _ in range(2000):
            samp = [c for ds in [random.choice(datasets) for _ in datasets] for c in ds_cells[ds]]
            if samp:
                boots.append(mean_rank(m, samp))
        lo, hi = np.percentile(boots, [2.5, 97.5])
        rows[m] = dict(mr=mean_rank(m, cells), lo=lo, hi=hi, geom=geom(m, cells), worst=worst_axis(m))
    order = sorted(METHODS, key=lambda m: rows[m]["mr"])
    tex = [r"\begin{tabular}{lccc}", r"\toprule",
           r"Method & Mean rank (95\% CI) & Geom.\ composite & Worst-axis \\", r"\midrule"]
    for m in order:
        r = rows[m]
        nm = r"\textbf{PRISM-GEP}" if m == "PRISM" else m
        tex.append(rf"{nm} & {r['mr']:.2f} [{r['lo']:.2f}, {r['hi']:.2f}] & {r['geom']:.3f} & {r['worst']:.3f} \\")
    tex += [r"\bottomrule", r"\end{tabular}"]
    (OUT / f"tab_robustness_agg_{tag}.tex").write_text(
        "% AUTO-GENERATED by scripts/build_unified_table1.py\n" + "\n".join(tex) + "\n", encoding="utf-8")
    # backing CSV so the mean-rank aggregates (e.g. PRISM 2.84 on the 9-ds grid) are locatable on disk
    csv_out = results_dir() / f"robustness_aggregates_{tag}.csv"
    csv_out.parent.mkdir(parents=True, exist_ok=True)
    pd.DataFrame([dict(method=m, mean_rank=round(rows[m]["mr"], 4), ci_lo=round(rows[m]["lo"], 4),
                       ci_hi=round(rows[m]["hi"], 4), geom_composite=round(rows[m]["geom"], 4),
                       worst_axis=round(rows[m]["worst"], 4), n_datasets=len(datasets), grid=tag)
                  for m in order]).to_csv(csv_out, index=False)
    print(f"\n=== aggregate ({tag}) === (backing CSV: {csv_out.name})")
    for m in order:
        r = rows[m]
        print(f"  {m:8} mean_rank {r['mr']:.2f} [{r['lo']:.2f},{r['hi']:.2f}]  geom {r['geom']:.3f}  worst-axis {r['worst']:.3f}")
    return rows


def welch(datasets):
    ps = pd.read_csv(PS)
    wins = tie = loss = 0
    details = []
    for ds in datasets:
        for me_ps in ["coherence", "coverage", "strength"]:
            pr = ps[(ps.dataset == ds) & (ps.variant == PS_VAR["PRISM"])][me_ps].dropna()
            if len(pr) < 2:
                continue
            for m in [x for x in METHODS if x != "PRISM"]:
                bl = ps[(ps.dataset == ds) & (ps.variant == PS_VAR[m])][me_ps].dropna()
                if len(bl) < 2:
                    continue
                t, p = stats.ttest_ind(pr, bl, equal_var=False)
                if p < 0.05 and pr.mean() > bl.mean():
                    wins += 1
                elif p < 0.05 and pr.mean() < bl.mean():
                    loss += 1
                else:
                    tie += 1
    return wins, tie, loss


def main():
    df = pd.read_csv(AGG).set_index("dataset")
    all15 = list(df.index)
    build_table(df, NINE, "9ds_opt0", "9-dataset unified")
    build_table(df, all15, "15ds_opt0", "15-dataset unified")
    print(f"WROTE tab_unified_9ds_opt0.tex + tab_unified_15ds_opt0.tex ({len(all15)} datasets)\n")
    for name, dss in [("9-DATASET (body)", NINE), ("15-DATASET (supp)", all15)]:
        mr, last, cells, pl, comp = aggregate(df, dss)
        pos = sorted(METHODS, key=lambda m: mr[m]).index("PRISM") + 1
        print(f"=== {name}: {cells} rankable cells ===")
        print("  mean rank:", ", ".join(f"{m} {mr[m]:.2f}" for m in sorted(METHODS, key=lambda m: mr[m])))
        print(f"  PRISM position {pos}/{len(METHODS)}; PRISM last-place {last['PRISM']}/{cells}  {pl if pl else '(never worst)'}")
        print(f"  geom composite: PRISM {comp['PRISM']:.3f}; " + ", ".join(f"{m} {comp[m]:.3f}" for m in ['cNMF', 'ProdLDA']))
    agg_table(df, NINE, "9ds")
    agg_table(df, all15, "15ds")
    w, t, l = welch(NINE)
    print(f"\nWelch PRISM_opt0 vs 5 baselines over 9 datasets x3 metrics: win {w} / tie {t} / loss {l}  (best-or-tied = {w+t}/{w+t+l})")
    w2, t2, l2 = welch(all15)
    print(f"Welch over 15 datasets: win {w2} / tie {t2} / loss {l2}  (best-or-tied = {w2+t2}/{w2+t2+l2})")


if __name__ == "__main__":
    main()
