"""Path helper for PRISM-GEP reproduction scripts.

Resolves the repository root and the canonical *release-layout* directories, so the
figure/table generators run from a clean clone rather than assuming any particular
authoring working-tree layout.

Root resolution order (first match wins):
  1. the ``$PRISM_GEP_ROOT`` environment variable, if set;
  2. an explicit root passed to the helper (e.g. from a script's ``--root`` CLI arg);
  3. the actual repository root — the parent of this ``scripts/`` directory.

Release layout the helpers map onto::

    results/          shipped metrics CSVs (full_metrics_combined_4config.csv,
                      full_metrics_perseed.csv, llm_coherence_all_v2.csv)
    paper/figures/    manuscript figure + table-fragment outputs (shipped, written here)
    data/             per-dataset counts + labels  (NOT shipped — see data/README.md)
    outputs/          pipeline intermediates       (NOT shipped — regenerated by the pipeline)

Note the split: importable method code (``bio/`` / ``prism_lib/``) always lives next to
``scripts/``, so ``sys.path`` insertion should keep using the script's own location; only
the *data / results / figure* roots are relocatable via ``$PRISM_GEP_ROOT``.
"""
from __future__ import annotations

import os
from pathlib import Path

__all__ = ["repo_root", "results_dir", "figures_dir", "data_dir", "outputs_dir"]


def repo_root(explicit: str | os.PathLike | None = None) -> Path:
    """Return the repository root (see module docstring for resolution order)."""
    if explicit:
        return Path(explicit).resolve()
    env = os.environ.get("PRISM_GEP_ROOT")
    if env:
        return Path(env).resolve()
    return Path(__file__).resolve().parent.parent


def results_dir(root: str | os.PathLike | None = None) -> Path:
    """Shipped metrics CSVs that back the paper's tables."""
    return repo_root(root) / "results"


def figures_dir(root: str | os.PathLike | None = None) -> Path:
    """Manuscript figure directory (``paper/figures/``); created if missing."""
    d = repo_root(root) / "paper" / "figures"
    d.mkdir(parents=True, exist_ok=True)
    return d


def data_dir(root: str | os.PathLike | None = None) -> Path:
    """Per-dataset counts + labels (not shipped; see ``data/README.md``)."""
    return repo_root(root) / "data"


def outputs_dir(root: str | os.PathLike | None = None) -> Path:
    """Pipeline intermediates (not shipped; regenerated by the pipeline)."""
    return repo_root(root) / "outputs"
